services:
  - type: web
    name: telegram-cash-app
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: API_ID
        value: "${API_ID}"
      - key: API_HASH
        value: "${API_HASH}"
      - key: PHONE
        value: "${PHONE}"
      - key: GROUP_EXP
        value: "${GROUP_EXP}"
      - key: GROUP_INC
        value: "${GROUP_INC}"
      - key: SESSION_FILE
        value: "render.session"  # отдельная сессия для Render
      - key: SKIP_AUTH
        value: "true"  # пропускаем авторизацию на Render